# Generated by Django 4.2.4 on 2023-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
