# Generated by Django 4.2.4 on 2023-09-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinus', '0002_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10),
        ),
    ]
