# Generated by Django 4.2.4 on 2023-09-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinus', '0006_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
