# Generated by Django 4.2.4 on 2023-09-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinus', '0007_remove_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('resolved', 'Решена'), ('in_progress', 'В процессе')], default='NEW', max_length=11),
        ),
    ]
