# Generated by Django 4.2.4 on 2023-09-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinus', '0008_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
