# Generated by Django 4.2.4 on 2023-10-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinus', '0010_transaction_assigned_user_transaction_resolved_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='resolved_user',
        ),
    ]
